-- 004: Decisions before step 5, 2026-09-24.

-- 1. A09 moves to T2 observe-only, with the reason logged on the test case. Reasons for the earlier
--    A11 and B08 moves are recorded the same way.
UPDATE rules SET test_case_ids = '{"must_trigger":["P06","H03"],"must_not_trigger":["A01","H04"],"observe":["A09","B08"],"reasons":{"A09":"T2 requires a revocable dependency plus use not permitted by terms. A DOM filter on the user''s own page may meet neither. The original concern was interface fragility, which T2 does not test.","B08":"Samples split 1 of 3. Substack has no content API, but public RSS feeds are a sanctioned syndication path; whether a cross-publication digest and search exceeds permitted use is unresolved. Observe until the terms question is settled."}}'
 WHERE id = 'T2';
UPDATE rules SET test_case_ids = '{"must_trigger":[],"must_not_trigger":["A11"],"reasons":{"A11":"T3 exempts ideas with a fully outsourced fulfillment path. Swag fulfillment APIs (SwagUp, Swag.com) provide one, so A11 does not meet T3 as written; the planted expectation was wrong, not the model."}}'
 WHERE id = 'T3';

-- 2. Proposed soft test T9 for interface fragility. Not active: Paul activates with npm run rule:activate.
INSERT OR IGNORE INTO rules (id, kind, text, test_case_ids, status, proposed_by) VALUES
 ('T9','soft_test','A core function depends on an undocumented interface (page markup, private endpoints) that can change without notice.','{"must_trigger":["A09"],"must_not_trigger":["A01"]}','proposed','paul');

-- 4. Idea status. Variants proposed by agents are proposed_variant until Paul promotes them; live runs
--    select active ideas only. Variants that already existed when this migration ran were generated by
--    replaying recorded traces and are archived.
ALTER TABLE ideas ADD COLUMN status TEXT NOT NULL DEFAULT 'active';
UPDATE ideas SET status = 'archived' WHERE parent_id IS NOT NULL;

-- Critic comparisons link to the stage result that holds their trace events.
ALTER TABLE comparisons ADD COLUMN stage_result_id TEXT REFERENCES stage_results(id);
