// Writes ledger/ideas/<id>.md for every idea with at least one stage result: generated header, kill
// gate result, viability brief, critic record. Generated from the store; never edited by hand.
//   npm run render
import fs from "node:fs";
import path from "node:path";
import { openDb, type Db } from "../src/store/db.js";
import { PATHS } from "../src/config.js";

function fence(v: unknown): string {
  return "```json\n" + JSON.stringify(v, null, 2) + "\n```";
}

export function renderIdea(db: Db, ideaId: string): string | null {
  const idea = db.getAgentSafeIdea(ideaId);
  if (!idea) return null;
  const kg = db.latestStageResult(ideaId, "kill_gate");
  const via = db.latestStageResult(ideaId, "viability");
  const critic = db.raw
    .prepare("SELECT * FROM stage_results WHERE idea_id = ? AND stage = 'critic' AND json_extract(payload_json, '$.kind') = 'standing' ORDER BY created_at DESC, rowid DESC LIMIT 1")
    .get(ideaId) as { payload_json: string; run_id: string } | undefined;
  if (!kg && !via && !critic) return null;
  const lines: string[] = [];
  lines.push(`<!-- generated by npm run render from data/factory.db; do not edit -->`);
  lines.push(`# ${idea.id}`);
  lines.push("");
  lines.push(`**Idea.** ${idea.idea}`);
  if (idea.customer) lines.push(`**Customer.** ${idea.customer}`);
  if (idea.verbatim_quote) lines.push(`**Source quote.** "${idea.verbatim_quote}"${idea.source_url ? ` (${idea.source_url})` : ""}`);
  if (idea.parent_id) lines.push(`**Variant of.** ${idea.parent_id}`);
  lines.push("");
  lines.push("## Kill gate");
  if (kg) {
    const p = JSON.parse(kg.payload_json);
    lines.push(`Verdict **${kg.verdict}**. Rules fired: ${JSON.parse(kg.rules_fired ?? "[]").join(", ") || "none"}. Model ${kg.model}, run ${kg.run_id}, trace ${kg.id}, $${kg.cost_usd.toFixed(4)}.`);
    lines.push("");
    if (p.tests?.length) {
      lines.push("| Test | Result | Evidence |");
      lines.push("|---|---|---|");
      for (const t of p.tests) lines.push(`| ${t.id} | ${t.result} | ${String(t.evidence ?? "").replace(/\|/g, "/")}${t.source_url ? ` <${t.source_url}>` : ""} |`);
      lines.push("");
    }
    if (p.flags?.length) {
      lines.push("Flags:");
      for (const f of p.flags) lines.push(`- ${f.id}: ${f.evidence}${f.obligations?.length ? ` Obligations: ${f.obligations.join("; ")}` : ""}`);
      lines.push("");
    }
    if (p.competitors?.length) {
      lines.push("Competitors found:");
      for (const c of p.competitors) lines.push(`- ${c.name}${c.relationship ? ` (${c.relationship})` : ""}${c.pricing ? `, ${c.pricing}` : ""}${c.url ? ` <${c.url}>` : ""}`);
      lines.push("");
    }
    if (p.proposed_variant) lines.push(`Proposed variant${p.runner?.variant_id ? ` (${p.runner.variant_id})` : ""}: ${p.proposed_variant.idea} (${p.proposed_variant.reason})`);
    if (p.runner?.overrides?.length) lines.push(`Runner overrides: ${p.runner.overrides.join("; ")}`);
    if (p.injection_seen?.length) lines.push(`Injection seen: ${p.injection_seen.length} item(s)`);
  } else lines.push("Not run.");
  lines.push("");
  lines.push("## Viability");
  if (via) {
    const p = JSON.parse(via.payload_json);
    lines.push(`Verdict **${via.verdict}**${p.runner?.missing?.length ? ` (missing: ${p.runner.missing.join("; ")})` : ""}. Model ${via.model}, run ${via.run_id}, trace ${via.id}, $${via.cost_usd.toFixed(4)}.`);
    if (p.runner?.unsourced_moved?.length) lines.push(`Unsourced URLs moved: ${p.runner.unsourced_moved.length}.`);
    lines.push("");
    if (via.doc_md) lines.push(via.doc_md.trim());
    else lines.push("No brief.");
    if (p.unsourced_claims?.length) {
      lines.push("");
      lines.push("Unsourced claims:");
      for (const u of p.unsourced_claims) lines.push(`- ${u}`);
    }
  } else lines.push("Not run.");
  lines.push("");
  lines.push("## Critic");
  if (critic) {
    const s = JSON.parse(critic.payload_json);
    lines.push(`Rank **${s.rank}** in run ${critic.run_id}: score ${s.score} (wins ${s.wins}, ties ${s.ties}, losses ${s.losses}, byes ${s.byes}), opponents' score ${s.opponentScore}.`);
    const comps = db.raw.prepare("SELECT * FROM comparisons WHERE run_id = ? AND (idea_a = ? OR idea_b = ?) ORDER BY round").all(critic.run_id, ideaId, ideaId) as any[];
    if (comps.length) {
      lines.push("");
      lines.push("| Round | Opponent | A first | B first | Result |");
      lines.push("|---|---|---|---|---|");
      for (const c of comps) {
        const me = c.idea_a === ideaId ? "A" : "B";
        const opp = c.idea_a === ideaId ? c.idea_b : c.idea_a;
        const outcome = c.result === "tie" ? "tie" : c.result === me ? "win" : "loss";
        lines.push(`| ${c.round} | ${opp} | ${c.order_ab === me ? "win" : "loss"} | ${c.order_ba === me ? "win" : "loss"} | ${outcome} |`);
      }
    }
  } else lines.push("Not run.");
  lines.push("");
  lines.push("<details><summary>Kill gate payload</summary>");
  lines.push("");
  lines.push(kg ? fence(JSON.parse(kg.payload_json)) : "none");
  lines.push("");
  lines.push("</details>");
  return lines.join("\n") + "\n";
}

export function renderAll(db: Db, outDir: string): number {
  fs.mkdirSync(outDir, { recursive: true });
  let n = 0;
  for (const idea of db.listAgentSafeIdeas()) {
    const md = renderIdea(db, idea.id);
    if (!md) continue;
    fs.writeFileSync(path.join(outDir, `${idea.id}.md`), md);
    n++;
  }
  return n;
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const db = openDb(PATHS.db);
  const dir = path.join(PATHS.ledger, "ideas");
  console.log(`rendered ${renderAll(db, dir)} idea files to ${path.relative(process.cwd(), dir)}`);
  db.close();
}
